[metadata.heroku]
  root-package = "github.com/heroku/fixture"
  go-version = "go1.6"
  install = [ "./cmd/...", "./foo" ]
  ensure = "false"
  additional-tools = ["github.com/golang-migrate/migrate"]
...
